[2018-08-28T18:42:40.368] [ERROR] articleDao - { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (d:\H5\Myblog\nodejs\myblog\node_modules\mysql\lib\protocol\Protocol.js:164:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (d:\H5\Myblog\nodejs\myblog\node_modules\mysql\lib\protocol\sequences\Sequence.js:129:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
    --------------------
    at Protocol._enqueue (d:\H5\Myblog\nodejs\myblog\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (d:\H5\Myblog\nodejs\myblog\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at PoolConnection.connect (d:\H5\Myblog\nodejs\myblog\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (d:\H5\Myblog\nodejs\myblog\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.releaseConnection (d:\H5\Myblog\nodejs\myblog\node_modules\mysql\lib\Pool.js:157:10)
    at Pool._removeConnection (d:\H5\Myblog\nodejs\myblog\node_modules\mysql\lib\Pool.js:277:8)
    at Pool._purgeConnection (d:\H5\Myblog\nodejs\myblog\node_modules\mysql\lib\Pool.js:258:8)
    at Ping.onOperationComplete [as _callback] (d:\H5\Myblog\nodejs\myblog\node_modules\mysql\lib\Pool.js:101:12)
    at Ping.Sequence.end (d:\H5\Myblog\nodejs\myblog\node_modules\mysql\lib\protocol\sequences\Sequence.js:88:24)
    at d:\H5\Myblog\nodejs\myblog\node_modules\mysql\lib\protocol\Protocol.js:398:18
    at Array.forEach (<anonymous>)
    at d:\H5\Myblog\nodejs\myblog\node_modules\mysql\lib\protocol\Protocol.js:397:13
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }
